# Generated by Django 5.2.6 on 2025-09-13 07:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FilmWork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="создано"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="изменено"
                    ),
                ),
                ("title", models.TextField(verbose_name="название")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="описание"
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True, null=True, verbose_name="рейтинг"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("movie", "фильм"), ("tv_show", "сериал")],
                        max_length=20,
                        verbose_name="тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "кинопроизведение",
                "verbose_name_plural": "кинопроизведения",
                "db_table": 'content"."film_work',
                "indexes": [
                    models.Index(fields=["title"], name="idx_film_work_title")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rating__gte", 0), ("rating__lte", 10)
                        ),
                        name="film_work_rating_check",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="создано"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="изменено"
                    ),
                ),
                (
                    "name",
                    models.TextField(unique=True, verbose_name="название"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "жанр",
                "verbose_name_plural": "жанры",
                "db_table": 'content"."genre',
                "indexes": [
                    models.Index(fields=["name"], name="idx_genre_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="создано"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="изменено"
                    ),
                ),
                ("full_name", models.TextField(verbose_name="полное имя")),
            ],
            options={
                "verbose_name": "персона",
                "verbose_name_plural": "персоны",
                "db_table": 'content"."person',
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="idx_person_full_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GenreFilmWork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="создано"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="изменено"
                    ),
                ),
                (
                    "film_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_app.filmwork",
                        verbose_name="кинопроизведение",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_app.genre",
                        verbose_name="жанр",
                    ),
                ),
            ],
            options={
                "verbose_name": "жанр-кинопроизведение",
                "verbose_name_plural": "жанры-кинопроизведения",
                "db_table": 'content"."genre_film_work',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("film_work", "genre"),
                        name="genre_film_work_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PersonFilmWork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="создано"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="изменено"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("actor", "актёр"),
                            ("director", "режиссёр"),
                            ("writer", "сценарист"),
                        ],
                        max_length=20,
                        verbose_name="роль",
                    ),
                ),
                (
                    "film_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_app.filmwork",
                        verbose_name="кинопроизведение",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content_app.person",
                        verbose_name="персона",
                    ),
                ),
            ],
            options={
                "verbose_name": "персона-кинопроизведение",
                "verbose_name_plural": "персоны-кинопроизведения",
                "db_table": 'content"."person_film_work',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("film_work", "person", "role"),
                        name="person_film_work_unique",
                    )
                ],
            },
        ),
    ]
